In [8]:
import numpy as np

x = np.array([10, 20])
x = np.expand_dims(x, axis=0)

y = np.array([[10, 20]])

z = np.zeros((1,2),dtype=np.uint8)

print(x)
print(x.shape)

print(y)
print(y.shape)

print(z)
print(z.shape)


[[10 20]]
(1, 2)
[[10 20]]
(1, 2)
[[0 0]]
(1, 2)
