# Basic shape
![explanation](https://i.stack.imgur.com/NWTQH.png)

In [6]:
import numpy as np

arr14 = np.array([1, 2, 3, 4])
print(arr14.shape)

(4,)


In [7]:
arr24 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr2d.shape)

(2, 4)


In [8]:
arr41 = np.array([[1], [2], [3], [4]])
print(arr41.shape)

(4, 1)


# operations 

In [10]:
a13 = np.array([1, 2, 3])
print(a13 + a13)

[2 4 6]


In [27]:
print(a13 * 3)

[3 6 9]


In [26]:
a31 = np.array([[1], [2], [3]])
print(a13 * a31)
print(a31 * a13)
print(np.multiply(a31, a13))
print(np.multiply(a13, a31))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


# matmul
* operation for matrix

In [21]:
print(np.matmul(a13, a31))
print(a13 @ a31) # it will be 1x1

[14]
[14]


In [28]:
# need a bracket around `a13`
print(np.matmul(a31, [a13])) 
print(a31 @ [a13]) # it will be 3x3

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
